image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - mvn clean package
  only:
    - 10-ci-cd

production:
  stage: deploy
  tags:
    - docker
  script:
    - java -jar target/Network-1.0-SNAPSHOT.jar
  only:
    - 10-ci-cd
