stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - echo $DB_PASSWORD
    - echo $SUDO_PASSWORD
    - whoami
    - mvn -Pprod clean package
    - cp target/Network-1.0-SNAPSHOT.jar /tmp/app.jar
  only:
    - 10-ci-cd

production:
  stage: deploy
  tags:
    - docker
  script:
    - echo $DB_PASSWORD
    - echo $SUDO_PASSWORD
    - java -jar /opt/network/prod/app.jar --spring.datasource.password=$DB_PASSWORD
  only:
    - 10-ci-cd
