image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - mvn clean
  only:
    - 10-ci-cd

production:
  stage: deploy
  tags:
    - docker
  script:
    - mvn spring-boot:run
  only:
    - 10-ci-cd
