image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - docker version
  artifacts:
    paths:
      - target/Network-1.0-SNAPSHOT.jar
  only:
    - 10-ci-cd

production:
  stage: deploy
  tags:
    - docker
  script:
    - echo $TOKEN_SECRET
  only:
    - 10-ci-cd
