stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - mvn -Pprod clean package
    - cp target/Network-1.0-SNAPSHOT.jar /opt/network/prod/app.jar
  only:
    - 10-ci-cd

production:
  stage: deploy
  tags:
    - docker
  script:
    - setsid nohup java -jar /opt/network/prod/app.jar --spring.datasource.password=$DB_PASSWORD > /tmp/nohup_log.out &
  only:
    - 10-ci-cd
