stages:
  - build
  - deploy

before_script:
  - chmod +x mvnw

build:
  stage: build
  tags:
    - docker
  script:
    - mvn -version
  artifacts:
    paths:
      - target/Network-1.0-SNAPSHOT.jar
  only:
    - 10-ci-cd

production:
  stage: deploy
  tags:
    - docker
  script:
    - echo $TOKEN_SECRET
  only:
    - 10-ci-cd
