spring:
  datasource:
    url: jdbc:mysql://localhost:3306/network?serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    show-sql: false

linkToChange:
  password: "http://localhost:8080/change-password"
  email: "http://localhost:8080/shift-email"

upload:
  path: "imgs"

log:
  path: "log/javapro"
