spring:
  datasource:
    url: jdbc:mysql://localhost:3306/network?serverTimezone=UTC
    username: root
    password: 1234567
  jpa:
    show-sql: true

  upload:
    path: "C:/Users/vitta/Desktop/Storage"