spring:
  datasource:
    url: jdbc:mysql://localhost:3306/network_prod?serverTimezone=UTC

linkToChange:
  password: "http://zerone.network:9000/change-password"
  email: "http://zerone.network:9000/shift-email"

upload:
  path:  "/home/jvmapps/photos"
