spring:
  datasource:
    url: jdbc:mysql://localhost:3306/network?serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    show-sql: true

linkToChange:
  password: "http://localhost:8080/change-password"
  email: "http://localhost:8080/shift-email"

upload:
  path: "C:/Users/Flutman/Desktop/Storage"